### PR TITLE
Update ruby.rml workflow:

### PR DESCRIPTION
**Pull request by ShreyaThapa**
Remove Ruby versions 2.4 and 2.5
 Add versions 3.0, 3.1 and 3.2

### CODE REVIEW

**Comment by spencerhunter** [comment]
@javierjulio before we version this library and publish a release we are also considering the possibility of upgrading some other dependencies. Do you have any feedback on whether any of the current dependencies and their versions should be updated? 

Appreciate your feedback and recommendations!

**Comment by javierjulio** [comment]
@spencerhunter sure, happy to help. I checked now but I think what you have is current. Faraday is at v2 and Hashie is at v5 but allows v3+ so that looks good. Was there something else or something specific? Let me know and I can review.

The GitHub Actions referenced could use an update. So for example, the workflow updated in this PR (I can't submit a suggestion since it's out of range) should use `actions/checkout@v4` now.

Also for the `ruby/setup-ruby` action there is no need to run bundle install manually since it will do so and cache gems with a single argument. I would [recommend replacing these lines](https://github.com/Dwolla/dwolla-v2-ruby/blob/main/.github/workflows/ruby.yml#L27-L33) with the following:

```yaml
      - name: Set up Ruby
        # https://github.com/ruby/setup-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
```

**Comment by ShreyaThapa** [comment]
Thanks so much for the prompt feedback and suggestion @javierjulio! 🙌 

Applied the changes you suggested to the workflow, and confirmed that they're working! All tests are passing. Will merge and publish a release soon!

**Comment by javierjulio** [comment]
@ShreyaThapa you're very welcome and thank you!

**Review by spencerhunter — APPROVED** [review]

**Pull request merged**
